### ISSUE TITLE
I am Muhammed Sultan from Jordan University studying Computer Science but I do not understand english very well. It would be helpful if I could get a tool to aid in my studies in my native language of Arabic.

### ISSUE THREAD

**Issue by KingUndeadCodes** [Allen-ISD-Computer-Science/REPO_CSTeachingApp_2024#12]

**Comment by Omar2we4** [comment]
The reason why it is under sprint 8 was because I had some technical obstacles with typing in the shell, I also was not feeling good on friday. Nonetheless i was able to get 30+ lines translated.

**Comment by KingUndeadCodes** [comment]
Why is there a user story in TODO? Also, If this issue is done, I believe we should close it.
